<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnidadSeeder extends Seeder
{
    public function run(): void
    {
        $now        = now();
        $connection = DB::connection('costos_tenant');

        $data = [
            [
                'descripcion'          => 'm³',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Metro Cúbico',
                'abreviatura_unidad'   => 'm³',
            ],
            [
                'descripcion'          => 'hh',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hora Hombre',
                'abreviatura_unidad'   => 'hh',
            ],
            [
                'descripcion'          => 'm²',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Metro Cuadrado',
                'abreviatura_unidad'   => 'm²',
            ],
            [
                'descripcion'          => 'und',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Unidad',
                'abreviatura_unidad'   => 'und',
            ],
            [
                'descripcion'          => '%mo',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado a mano de obra desde otro grupo diferente a mano de obra',
                'abreviatura_unidad'   => '%mo',
            ],
            [
                'descripcion'          => 'hom',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hombre - Mes',
                'abreviatura_unidad'   => 'hom',
            ],
            [
                'descripcion'          => 'und- mes',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Unidad Mes',
                'abreviatura_unidad'   => 'und- mes',
            ],
            [
                'descripcion'          => 'semana',
                'descripcion_singular' => 'Semana',
                'orden'                => '3',
                'informacion_unidad'   => 'Semana',
                'abreviatura_unidad'   => 'semana',
            ],
            [
                'descripcion'          => 'meses',
                'descripcion_singular' => 'Mes',
                'orden'                => '4',
                'informacion_unidad'   => 'Mes',
                'abreviatura_unidad'   => 'meses',
            ],
            [
                'descripcion'          => 'años',
                'descripcion_singular' => 'Año',
                'orden'                => '5',
                'informacion_unidad'   => 'Años',
                'abreviatura_unidad'   => 'años',
            ],
            [
                'descripcion'          => 'kg',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Kilogramo',
                'abreviatura_unidad'   => 'kg',
            ],
            [
                'descripcion'          => 'vrlla',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Varilla',
                'abreviatura_unidad'   => 'vrlla',
            ],
            [
                'descripcion'          => 't',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Tonelada',
                'abreviatura_unidad'   => 't',
            ],
            [
                'descripcion'          => 'pza',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Pieza',
                'abreviatura_unidad'   => 'pza',
            ],
            [
                'descripcion'          => 'gln',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Galón',
                'abreviatura_unidad'   => 'gln',
            ],
            [
                'descripcion'          => 'mll',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Millar',
                'abreviatura_unidad'   => 'mll',
            ],
            [
                'descripcion'          => 'par',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Juego ',
                'abreviatura_unidad'   => 'par',
            ],
            [
                'descripcion'          => 'm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Metro Lineal',
                'abreviatura_unidad'   => 'm',
            ],
            [
                'descripcion'          => 'rll',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Rollo',
                'abreviatura_unidad'   => 'rll',
            ],
            [
                'descripcion'          => 'bol',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Bolsa',
                'abreviatura_unidad'   => 'bol',
            ],
            [
                'descripcion'          => 'bal',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Balde',
                'abreviatura_unidad'   => 'bal',
            ],
            [
                'descripcion'          => 'cja',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Caja',
                'abreviatura_unidad'   => 'cja',
            ],
            [
                'descripcion'          => 'cnt',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Ciento',
                'abreviatura_unidad'   => 'cnt',
            ],
            [
                'descripcion'          => 'p2',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Pie Cuadrado',
                'abreviatura_unidad'   => 'p2',
            ],
            [
                'descripcion'          => 'lt',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Litro',
                'abreviatura_unidad'   => 'lt',
            ],
            [
                'descripcion'          => 'hm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hora Máquina',
                'abreviatura_unidad'   => 'hm',
            ],
            [
                'descripcion'          => 'ha',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hectárea',
                'abreviatura_unidad'   => 'ha',
            ],
            [
                'descripcion'          => 'gbl',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Global',
                'abreviatura_unidad'   => 'gbl',
            ],
            [
                'descripcion'          => 'pln',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Plancha',
                'abreviatura_unidad'   => 'pln',
            ],
            [
                'descripcion'          => 'mes',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Mes',
                'abreviatura_unidad'   => 'mes',
            ],
            [
                'descripcion'          => 'cjt',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Conjunto',
                'abreviatura_unidad'   => 'cjt',
            ],
            [
                'descripcion'          => 'tub',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Tubería',
                'abreviatura_unidad'   => 'tub',
            ],
            [
                'descripcion'          => 'dia',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'día',
                'abreviatura_unidad'   => 'dia',
            ],
            [
                'descripcion'          => 'pto',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Punto',
                'abreviatura_unidad'   => 'pto',
            ],
            [
                'descripcion'          => 'he',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hora equipo',
                'abreviatura_unidad'   => 'he',
            ],
            [
                'descripcion'          => 'km',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Kilómetro',
                'abreviatura_unidad'   => 'km',
            ],
            [
                'descripcion'          => 'vje',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Viaje',
                'abreviatura_unidad'   => 'vje',
            ],
            [
                'descripcion'          => 's/',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Costo unitario',
                'abreviatura_unidad'   => 's/',
            ],
            [
                'descripcion'          => 'jgo',
                'descripcion_singular' => '',
                'orden'                => '0',
                'informacion_unidad'   => 'Juego',
                'abreviatura_unidad'   => 'jgo',
            ],
            [
                'descripcion'          => 'est',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Estimado',
                'abreviatura_unidad'   => 'est',
            ],
            [
                'descripcion'          => '%',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado sobre una suma total de grupo',
                'abreviatura_unidad'   => '%',
            ],
            [
                'descripcion'          => 'kit',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Juego',
                'abreviatura_unidad'   => 'kit',
            ],
            [
                'descripcion'          => 'tm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Tonelada métrica',
                'abreviatura_unidad'   => 'tm',
            ],
            [
                'descripcion'          => '%eq',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado a  equipos desde otro grupo diferente a equipos',
                'abreviatura_unidad'   => '%eq',
            ],
            [
                'descripcion'          => 'hr',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Hora',
                'abreviatura_unidad'   => 'hr',
            ],
            [
                'descripcion'          => '%%',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado a una suma total de grupo incluido otros %',
                'abreviatura_unidad'   => '%%',
            ],
            [
                'descripcion'          => '%mt',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado a materiales desde otro grupo diferente a materiales',
                'abreviatura_unidad'   => '%mt',
            ],
            [
                'descripcion'          => '%pu',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '% aplicado al total de un precio unitario',
                'abreviatura_unidad'   => '%pu',
            ],
            [
                'descripcion'          => 'sem',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Semana',
                'abreviatura_unidad'   => 'sem',
            ],
            [
                'descripcion'          => 'var',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Varilla',
                'abreviatura_unidad'   => 'var',
            ],
            [
                'descripcion'          => 'ML',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Metro Lineal',
                'abreviatura_unidad'   => 'ML',
            ],
            [
                'descripcion'          => 'caj',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Caja',
                'abreviatura_unidad'   => 'caj',
            ],
            [
                'descripcion'          => 'plg',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Pliego',
                'abreviatura_unidad'   => 'plg',
            ],
            [
                'descripcion'          => 'estm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Estimado',
                'abreviatura_unidad'   => 'estm',
            ],
            [
                'descripcion'          => 'Cor',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Corte',
                'abreviatura_unidad'   => 'Cor',
            ],
            [
                'descripcion'          => 'cm²',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Centímetro cuadrado',
                'abreviatura_unidad'   => 'cm²',
            ],
            [
                'descripcion'          => 'cm³',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Centímetro cúbico',
                'abreviatura_unidad'   => 'cm³',
            ],
            [
                'descripcion'          => 'm³k',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Metro cubico kilometro',
                'abreviatura_unidad'   => 'm³k',
            ],
            [
                'descripcion'          => 'UNID.MES',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Unidad Mes',
                'abreviatura_unidad'   => 'UNID.MES',
            ],
            [
                'descripcion'          => 'glb',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'glb',
            ],
            [
                'descripcion'          => 'gal',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'gal',
            ],
            [
                'descripcion'          => 'Kxm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'Kxm',
            ],
            [
                'descripcion'          => 'h',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'h',
            ],
            [
                'descripcion'          => 'l',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'l',
            ],
            [
                'descripcion'          => 'ton',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'ton',
            ],
            [
                'descripcion'          => 'plc',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'plc',
            ],
            [
                'descripcion'          => 'hor',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'hora',
                'abreviatura_unidad'   => 'hor',
            ],
            [
                'descripcion'          => 'sco',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Saco',
                'abreviatura_unidad'   => 'sco',
            ],
            [
                'descripcion'          => 'lb',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Libra',
                'abreviatura_unidad'   => 'lb',
            ],
            [
                'descripcion'          => 'cm',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Centímetro',
                'abreviatura_unidad'   => 'cm',
            ],
            [
                'descripcion'          => 'blt',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => 'Bulto',
                'abreviatura_unidad'   => 'blt',
            ],
            [
                'descripcion'          => 'cto',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'cto',
            ],
            [
                'descripcion'          => 'hja',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'hja',
            ],
            [
                'descripcion'          => 'gl',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'gl',
            ],
            [
                'descripcion'          => 'bls',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'bls',
            ],
            [
                'descripcion'          => 'PG2',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'PG2',
            ],
            [
                'descripcion'          => 'tot',
                'descripcion_singular' => '',
                'orden'                => '',
                'informacion_unidad'   => '',
                'abreviatura_unidad'   => 'tot',
            ],
        ];

        foreach ($data as $item) {
            $connection->table('unidad')->updateOrInsert(
                ['descripcion' => $item['descripcion']], // ← clave de búsqueda (es unique)
                array_merge($item, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }
}