export interface RawNormativeLeaf {
    title: string;
    label: string;
    iluminancia_lux: number;
    UGR: number | null;
    Uo: number | null;
    Ra: number | null;
    requisitos_especificos: string | null;
}

export interface RawNormativeBranch {
    title: string;
    subsections?: Array<RawNormativeBranch | RawNormativeLeaf>;
    subsubsections?: RawNormativeLeaf[];
}

export const en12464Regulations: RawNormativeBranch[] = [
    {
        title: 'Vivienda',
        subsections: [
            {
                title: 'Zona privada',
                subsubsections: [
                    {
                        title: 'Dormitorio',
                        label: 'Dormitorio, sala de estar, comedor, sala de juegos, sala de television y similares',
                        iluminancia_lux: 50,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Baño',
                        label: 'Bano, area de ducha, banera y similares',
                        iluminancia_lux: 100,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Baño espejo',
                        label: 'Bano, area de espejo y similares',
                        iluminancia_lux: 500,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Cocina',
                        label: 'Cocina, area de lavado y similares',
                        iluminancia_lux: 300,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Sala',
                        label: 'Sala de estar, comedor, sala de juegos, sala de television y similares',
                        iluminancia_lux: 100,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Comedor',
                        label: 'Comedor, sala de estar, sala de juegos, sala de television y similares',
                        iluminancia_lux: 100,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Estudio',
                        label: 'Estudios, almacenes, depositos, walking closet, cuartos de trabajo domestico y similares',
                        iluminancia_lux: 100,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Patio',
                        label: 'Patios, terrazas, balcones y similares',
                        iluminancia_lux: 20,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Estacionamiento bajo techo',
                        label: 'Estacionamientos bajo techo y similares',
                        iluminancia_lux: 50,
                        UGR: null,
                        Uo: null,
                        Ra: null,
                        requisitos_especificos: 'Ninguno',
                    },
                ],
            },
            {
                title: 'Zonas comunes',
                subsubsections: [
                    {
                        title: 'Vestibulos de entrada',
                        label: 'Vestibulos de entrada, pasillos, escaleras y similares',
                        iluminancia_lux: 100,
                        UGR: 22,
                        Uo: 0,
                        Ra: 60,
                        requisitos_especificos: 'Debe ser accesible',
                    },
                    {
                        title: 'Salas publicas',
                        label: 'Salas de estar publicas, comedores publicos, salas de juegos publicas y similares',
                        iluminancia_lux: 200,
                        UGR: 22,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Debe ser accesible',
                    },
                    {
                        title: 'Area de circulacion',
                        label: 'Areas de circulacion y pasillos en edificios de vivienda colectiva y similares',
                        iluminancia_lux: 100,
                        UGR: 28,
                        Uo: 0,
                        Ra: 40,
                        requisitos_especificos: 'Debe ser accesible',
                    },
                    {
                        title: 'Escaleras y pasillos',
                        label: 'Escaleras, escaleras mecanicas y transportadores de personas',
                        iluminancia_lux: 150,
                        UGR: 25,
                        Uo: 0.4,
                        Ra: 40,
                        requisitos_especificos: 'Iluminancia a nivel del suelo',
                    },
                    {
                        title: 'Ascensores y montacargas',
                        label: 'Ascensores, montacargas y similares',
                        iluminancia_lux: 100,
                        UGR: 25,
                        Uo: 0.4,
                        Ra: 40,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Rampas y andenes',
                        label: 'Rampas, andenes, patios de carga y similares',
                        iluminancia_lux: 150,
                        UGR: 25,
                        Uo: 0.4,
                        Ra: 40,
                        requisitos_especificos: 'Ninguno',
                    },
                ],
            },
        ],
    },
    {
        title: 'Educacion',
        subsections: [
            {
                title: 'Sala de juegos',
                label: 'Salas de juegos, salas de television y similares',
                iluminancia_lux: 300,
                UGR: 22,
                Uo: 0.4,
                Ra: 80,
                requisitos_especificos:
                    'Debe evitarse altas luminancias en las direcciones de vision desde abajo',
            },
            {
                title: 'Guarderias',
                label: 'Guarderias, salas de juegos, salas de television y similares',
                iluminancia_lux: 300,
                UGR: 22,
                Uo: 0.4,
                Ra: 80,
                requisitos_especificos:
                    'Debe evitarse altas luminancias en las direcciones de vision desde abajo',
            },
            {
                title: 'Sala de manualidades',
                label: 'Salas de manualidades, laboratorios, talleres y similares',
                iluminancia_lux: 300,
                UGR: 22,
                Uo: 0.4,
                Ra: 80,
                requisitos_especificos:
                    'Debe evitarse altas luminancias en las direcciones de vision desde abajo',
            },
            {
                title: 'Aula de profesores',
                label: 'Aulas de profesores, salas de reuniones y similares',
                iluminancia_lux: 300,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'La iluminacion debe ser controlable',
            },
            {
                title: 'Aulas para clases nocturnas',
                label: 'Aulas para clases nocturnas y de educación de adultos',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'La iluminacion debe ser controlable',
            },
            {
                title: 'Sala de lectura',
                label: 'Sala de lectura',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'La iluminacion debe ser controlable',
            },
            {
                title: 'Zona de pizarra',
                label: 'Zona de pizarra',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.7,
                Ra: 80,
                requisitos_especificos:
                    'Deben evitarse las refl exiones especulares El presentador/profesor debe iluminarse con la iluminancia vertical adecuada',
            },
            {
                title: 'Mesa de demortraciones',
                label: 'Mesa de demortraciones',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.7,
                Ra: 80,
                requisitos_especificos: 'En salas de lectura 750 LX',
            },
            {
                title: 'Locales de artes',
                label: 'Locales de artes y oficios',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'Ninguno',
            },
            {
                title: 'Locales de artes escuelas',
                label: 'Locales de artes (en escuelas de arte)',
                iluminancia_lux: 750,
                UGR: 19,
                Uo: 0.7,
                Ra: 90,
                requisitos_especificos: '5000k =< TCP < 6500 k',
            },
            {
                title: 'Salas de dibujo',
                label: 'Sala de dibujo técnico',
                iluminancia_lux: 750,
                UGR: 19,
                Uo: 0.7,
                Ra: 80,
                requisitos_especificos: 'Ninguno',
            },
            {
                title: 'Locales de prácticas',
                label: 'Locales de prácticas y laboratorios',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'Ninguno',
            },
            {
                title: 'Aulas de manualidades',
                label: 'Aulas de manualidades',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'Ninguno',
            },
            {
                title: 'Taller de enseñanza',
                label: 'Taller de enseñanza',
                iluminancia_lux: 500,
                UGR: 19,
                Uo: 0.6,
                Ra: 80,
                requisitos_especificos: 'Ninguno',
            },
        ],
    },
    {
        title: 'Salud',
        subsections: [
            {
                title: 'Zonas de hospitalización',
                subsubsections: [
                    {
                        title: 'Habitación de paciente',
                        label: 'Habitación individual o compartida para paciente',
                        iluminancia_lux: 100,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos:
                            'Iluminación atenuable para descanso',
                    },
                    {
                        title: 'Baño de paciente',
                        label: 'Baño asociado a habitación',
                        iluminancia_lux: 200,
                        UGR: 22,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Sala de estar',
                        label: 'Sala de estar y convivencia en zona de hospitalización',
                        iluminancia_lux: 150,
                        UGR: 22,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Ambiente relajante',
                    },
                    {
                        title: 'Estación de enfermería',
                        label: 'Estación de trabajo de enfermería',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos:
                            'Buena visualización de pantallas',
                    },
                ],
            },
            {
                title: 'Zonas quirúrgicas y críticas',
                subsubsections: [
                    {
                        title: 'Quirófano',
                        label: 'Quirófano general',
                        iluminancia_lux: 40000,
                        UGR: 16,
                        Uo: 0.7,
                        Ra: 90,
                        requisitos_especificos:
                            'Iluminación especializada sin sombras, CRI ≥ 90',
                    },
                    {
                        title: 'Sala de recuperación',
                        label: 'Sala de recuperación post-anestésica',
                        iluminancia_lux: 200,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Iluminación atenuable',
                    },
                    {
                        title: 'UCI adulto',
                        label: 'Unidad de Cuidados Intensivos para adultos',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos:
                            'Controlable por el paciente y personal',
                    },
                    {
                        title: 'UCI pediátrica',
                        label: 'Unidad de Cuidados Intensivos pediátrica',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos:
                            'Iluminación suave y controlable',
                    },
                    {
                        title: 'Sala de procedimientos',
                        label: 'Sala de procedimientos quirúrgicos menores',
                        iluminancia_lux: 1000,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 90,
                        requisitos_especificos: 'Iluminación focalizada',
                    },
                    {
                        title: 'Sala de parto',
                        label: 'Sala de atención de parto',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 90,
                        requisitos_especificos: 'Iluminación cálida y clara',
                    },
                ],
            },
            {
                title: 'Consultorios y diagnóstico',
                subsubsections: [
                    {
                        title: 'Consultorio médico',
                        label: 'Consulta externa general',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'Luz neutra, buena definición',
                    },
                    {
                        title: 'Sala de exploración',
                        label: 'Revisión médica y exploración física',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'Uniforme, sin sombras',
                    },
                    {
                        title: 'Laboratorio clínico',
                        label: 'Análisis de muestras biológicas',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 90,
                        requisitos_especificos:
                            'Precisión en reconocimiento de colores',
                    },
                    {
                        title: 'Radiología diagnóstica',
                        label: 'Sala de rayos X, resonancia, tomografía',
                        iluminancia_lux: 100,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos:
                            'Iluminación indirecta para monitores',
                    },
                    {
                        title: 'Ultrasonido',
                        label: 'Sala de ecografía',
                        iluminancia_lux: 200,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Sala de endoscopía',
                        label: 'Procedimientos endoscópicos',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 90,
                        requisitos_especificos: 'Iluminación focal en campo',
                    },
                ],
            },
            {
                title: 'Servicios de apoyo',
                subsubsections: [
                    {
                        title: 'Farmacia',
                        label: 'Dispensación y almacenamiento de medicamentos',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos:
                            'Buena legibilidad de etiquetas',
                    },
                    {
                        title: 'Central de esterilización',
                        label: 'Área de limpieza y esterilización de instrumental',
                        iluminancia_lux: 500,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 90,
                        requisitos_especificos: 'Inspección visual minuciosa',
                    },
                    {
                        title: 'Almacén médico',
                        label: 'Almacén de suministros y equipos médicos',
                        iluminancia_lux: 200,
                        UGR: 25,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Lavandería',
                        label: 'Área de lavado y procesado de ropa hospitalaria',
                        iluminancia_lux: 300,
                        UGR: 22,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Cocina dietética',
                        label: 'Preparación de alimentos para pacientes',
                        iluminancia_lux: 300,
                        UGR: 22,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Higiene y limpieza',
                    },
                ],
            },
            {
                title: 'Zonas de circulación y espera',
                subsubsections: [
                    {
                        title: 'Pasillos generales',
                        label: 'Pasillos de circulación interna',
                        iluminancia_lux: 150,
                        UGR: 22,
                        Uo: 0,
                        Ra: 60,
                        requisitos_especificos: 'Uniformidad y orientación',
                    },
                    {
                        title: 'Vestíbulos',
                        label: 'Vestíbulo de entrada y recepción',
                        iluminancia_lux: 300,
                        UGR: 22,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Buena impresión visual',
                    },
                    {
                        title: 'Salas de espera',
                        label: 'Zonas de espera para pacientes y acompañantes',
                        iluminancia_lux: 200,
                        UGR: 22,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Ambiente cálido y relajante',
                    },
                    {
                        title: 'Ascensores',
                        label: 'Cabinas de ascensor',
                        iluminancia_lux: 100,
                        UGR: 25,
                        Uo: 0.4,
                        Ra: 60,
                        requisitos_especificos: 'Ninguno',
                    },
                    {
                        title: 'Escaleras',
                        label: 'Escaleras de emergencia y circulación',
                        iluminancia_lux: 150,
                        UGR: 25,
                        Uo: 0.4,
                        Ra: 60,
                        requisitos_especificos: 'Iluminancia a nivel del suelo',
                    },
                    {
                        title: 'Estacionamiento cubierto',
                        label: 'Estacionamiento para pacientes y personal',
                        iluminancia_lux: 50,
                        UGR: 28,
                        Uo: 0,
                        Ra: 60,
                        requisitos_especificos: 'Seguridad y vigilancia',
                    },
                ],
            },
            {
                title: 'Zonas administrativas',
                subsubsections: [
                    {
                        title: 'Oficinas',
                        label: 'Oficinas administrativas y dirección',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'Sin reflejos en pantallas',
                    },
                    {
                        title: 'Sala de juntas',
                        label: 'Sala de reuniones y capacitación',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'Controlable',
                    },
                    {
                        title: 'Archivo',
                        label: 'Almacén de expedientes y documentos',
                        iluminancia_lux: 200,
                        UGR: 25,
                        Uo: 0,
                        Ra: 80,
                        requisitos_especificos: 'Acceso fácil a fichas',
                    },
                ],
            },
            {
                title: 'Áreas de emergencia',
                subsubsections: [
                    {
                        title: 'Urgencias triage',
                        label: 'Área de clasificación de pacientes',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'Buena visualización',
                    },
                    {
                        title: 'Sala de trauma',
                        label: 'Sala de reanimación y trauma',
                        iluminancia_lux: 1000,
                        UGR: 19,
                        Uo: 0.7,
                        Ra: 90,
                        requisitos_especificos:
                            'Iluminación intensa y sin sombras',
                    },
                    {
                        title: 'Observación',
                        label: 'Área de observación y corta estancia',
                        iluminancia_lux: 200,
                        UGR: 19,
                        Uo: 0.4,
                        Ra: 80,
                        requisitos_especificos: 'Ninguno',
                    },
                ],
            },
        ],
    },
    { title: 'Industria', subsections: [] },
    { title: 'Comercio', subsections: [] },
    { title: 'Oficinas', subsections: [] },
    { title: 'Servicios comunales', subsections: [] },
    { title: 'Deportes', subsections: [] },   
    { title: 'Transporte', subsections: [] },
    { title: 'Estacionamientos', subsections: [] },
];

export const iesnaRegulations: RawNormativeBranch[] = [
    {
        title: 'Residential',
        subsections: [
            {
                title: 'General',
                subsubsections: [
                    {
                        title: 'Living Room',
                        label: 'Living room, general lighting',
                        iluminancia_lux: 150,
                        UGR: 19,
                        Uo: 0.5,
                        Ra: 80,
                        requisitos_especificos: 'IESNA category C',
                    },
                    {
                        title: 'Kitchen',
                        label: 'Kitchen, general lighting',
                        iluminancia_lux: 300,
                        UGR: 22,
                        Uo: 0.5,
                        Ra: 80,
                        requisitos_especificos: 'IESNA category D',
                    },
                    {
                        title: 'Bedroom',
                        label: 'Bedroom, general lighting',
                        iluminancia_lux: 100,
                        UGR: 19,
                        Uo: 0.5,
                        Ra: 80,
                        requisitos_especificos: 'IESNA category B',
                    },
                ]
            }
        ]
    },
    {
        title: 'Commercial',
        subsections: [
            {
                title: 'Office',
                subsubsections: [
                    {
                        title: 'Open Office',
                        label: 'Open plan office, intensive VDT use',
                        iluminancia_lux: 400,
                        UGR: 16,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'IESNA category E',
                    },
                    {
                        title: 'Conference Room',
                        label: 'Conference and meeting rooms',
                        iluminancia_lux: 300,
                        UGR: 19,
                        Uo: 0.6,
                        Ra: 80,
                        requisitos_especificos: 'IESNA category D',
                    }
                ]
            }
        ]
    }
];
